PBC_IP="10.10.10.3"
PBC_PORT=10002
UVC_IP="10.10.10.1"
UVC_PORT=11011
HBC_IP="10.10.10.2"
HBC_PORT=10002
TEAMCITY_URL="http://10.14.14.14"
PBC_BUILD_CONFIG_ID="Aurora_Pbc_FeaturesBugs"
HBC_BUILD_CONFIG_ID="Aurora_Hbc2_FeaturesBugs"
PBC_INCORRECT_PARAMETER_MESSAGE="Incorrect Parameter, Please use --help for all the listed functions."
UVC_VIDEO_STREAM_PORT=11001
UVC_CLI_PORT=11003
UVC_VIDEO_HEADER_SIZE=48
SOCKET_CLOSED="Socket closed by server"
RECIEVED_OTHER_MSG="Received other message, ignoring"
FRAME_HEADER_MARKER=b"\x5b\x24\x23\x5d"  # marker indicating frame start [$#] (similar to CPP streamservice)
CAMERA_COMMAND_LEFT=b"\x6c\x65\x66\x74"  # 'left'
CAMERA_COMMAND_RIGHT=b"\x72\x69\x67\x68\x74"  # 'right'
CAMERA_COMMAND_GRAB=b"\x67\x72\x61\x62"  # 'grab'
CAMERA_COMMAND_LIVE=b"\x6c\x69\x76\x65"   # 'live'
MAX_BUFFER_SIZE=20 * 1024 * 1024
RECIEVED_CHUNK_SIZE=64 * 1024
CAMERA_STRING_LEFT='left'
CAMERA_STRING_RIGHT='right'
CAMERA_STRING_WIDE='wide'
CAMERA_STRING_AUTO='auto'
UV_ON="Turn on UV"
TURN_UV_ON='hbc starttreatment'
TURN_UV_OFF='hbc canceltreatment'
UV_OFF="Turn off UV"
BUFFER_SIZE = 1024
RECONNECT_DELAY = 5
BG_COLOR_BLACK="black"
BG_COLOR_GREEN="green"
STREAM_RESPONSE_LEFT="Setting datapath to stream left camera"
STREAM_RESPONSE_RIGHT="Setting datapath to stream right"
STREAM_RESPONSE_WIDE="Setting datapath to stream wide camera"
STREAM_RESPONSE_AUTO="Setting datapath to stream to auto"
UV_MILLIWATT_SELFTEST_VALUE=30

# Commonly used variable constants
ABOUT="About"
STATUS="Status"
CONTROLS="Controls"
DEVICE_LIMITS="Device Limits"
DEVICE_SETTINGS="Device Settings"
CAL_TABLE="Calibration Table"
UPDATE_FW_PBC_FROM_FILE="Install PBC\n Firmware from file"
UPDATE_FW_HBC_FROM_FILE="Install HBC\n Firmware from file"
IS_CAL_VALID="Is Calibration Valid"
IS_CAMERA_WORKING="Is Camera Working"
CHECK_UVC_ERRORS="Check UVC Errors"
UVC_START_TREATMENT="Start Treatment"
UVC_START_PAUSE_RESUME_TREATMENT="Start -> Pause -> Resume"
UVC_GET_TREATMENT_DATA="Get \nTreatment Data"
UVC_PAUSE_TIME="Pause (sec)"
CONNECT_UVC="Connect to UVC"
UVC_NETCAT="UVC 11003"
STOP_STREAM="Stop Stream"
HBC_SELF_TEST="Run\nHBC self test"
SET_GET_NIR_LED="Set and get\nNIR LED"
SET_GET_FIXATION_LED="Set and get\nfixation LED"
SET_GET_CAMERA_TRIGGERS="Set and get\ncamera triggers"
SET_DEVICE_SERIAL_NUMBER="Set Serial Number"
START_UV_DIAGNOSTIC="Start\nUV diagnostic"
START_HBC_CALIBRATION="Start\nHBC Calibration"
START_PULSED_TREATMENT="Start\npulsed treatment"
START_CONTINUOUS_TREATMENT="Start\ncontinuous treatment"
START_DEMO_TREATMENT="Start\ndemo treatment"
IRRADIANCE="Irradiance (3-45 mW/cm²)"
TREATMENT_TIME="Treatment time (ms)"
PULSE_ON="Pulse on(ms)"
PULSE_OFF="Pulse off(ms)"
GAIN="Gain (1-25)"
OFFSET="Offset (1-25)"
SET_DISTANCE_SENSOR_SETTINGS="Set distance \nsensor settings"
START_DISTANCE_SENSOR_RANGING="Start Ranging"
STOP_DISTANCE_SENSOR_RANGING="Stop Ranging"
UV_DEVICE_SETTINGS="Set UV \ndevice settings"
UV_DEVICE_SETTINGS_PD1="pd1 gain count"
UV_DEVICE_SETTINGS_PD2="pd2 gain count"
UV_DEVICE_SETTINGS_PD3="pd3 gain count"
UV_DEVICE_SETTINGS_PI="pi gain count"
RUNTIME="Time to run sensor (sec)"
MOVE_MOTORS_X="X Axis pos [(±)0.1-9.9mm]"
MOVE_MOTORS_Y="Y Axis pos [(±)0.1-9.9mm]"
MOVE_MOTORS_Z="Z Axis pos [(±)0.1-9.9mm]"
MOVE_MOTORS="Move Motor"
SET_FAN_CONTROLS="Set UV/Head Fan"
HOME_MOTOR_CONTROLS="Home the motors"
UV_FAN="UV Fan"
HEAD_FAN="Head Fan"
BRAKE="Brake On/Off"
PBC_BRAKE_CONTROLS="PBC Brake"
FAN="Fan On/Off"
PBC_FAN_CONTROLS="PBC Fan"
LED_RED="Red"
LED_BLUE="Blue"
LED_GREEN="Green"
STATIC_COLOR_EFFECT="Static LED"
PULSED_COLOR_EFFECT="Pulsed LED"
RAINBOW_COLOR_EFFECT="Rainbow LED"
CHASING_RAINBOW_COLOR_EFFECT="Chasing Rainbow LED"
STOP_ALL_LEDS="Stop LED's"
PULSE_PERIOD="Pulse time"
USB_PORT1_CH1="port 1 Ch 1"
USB_PORT2_CH1="port 2 Ch 1"
USB_PORT1_CH2="port 1 Ch 2"
USB_PORT2_CH2="port 2 Ch 2"
USB_CONTROL="USB Control"
RESET_PBC_TO_DEFAULT="Reset PBC\nto Default"
RESET_HBC_TO_DEFAULT="Reset HBC\nto Default"

# Commonly used protobuf variables
PROTO_ABOUT="about"
PROTO_STATUS="status"
PROTO_CONTROLS="controls"
PROTO_DEVICE_LIMITS="device_limits"
PROTO_DEVICE_SETTINGS="device_settings"
PROTO_CAL_TABLE="calibration_table"
PROTO_SELFTESTRESULT="self_test_result"
PROTO_DIAGNOSTICRESULT="diagnostic_result"
PROTO_CALIBRATIONRESULT="calibration_result"
PROTO_TREATMENTRESULT="treatment_result"
PROTO_DISTANCE_SETTINGS_RESULT="distance_sensor_ranging_result"
PROTO_MOVE_MOTORS="move_motors"
PROTO_SET_FAN_CONTROLS="set_fan_controls"
PROTO_BRAKE_CONTROLS="brake_enable"
PROTO_FAN_CONTROLS="fans_enable"
PROTO_LOG_ENTRY="log_entry"

# Firmware Updater dialog variables
FIRMWARE_UPDATER="Firmware Updater"
PASSWORD_ENTRY="Enter Password:"
SELECT_BINARY="Select Firmware Binary"

# Default protobuf variables
PROTO_DEFAULT_FREQ=7
PROTO_DEFAULT_DUR=30
PROTO_DEFAULT_NIR=80
PROTO_DEFAULT_IRR=30
PROTO_DEFAULT_DAC=5000
PROTO_DEFAULT_INT=10
PROTO_DEFAULT_PD1_GC=0
PROTO_DEFAULT_PD2_GC=512
PROTO_DEFAULT_PD3_GC=256
PROTO_DEFAULT_PI_GC=1023